const { z } = require('zod');

// Shared enums
const RELATIONSHIP_TYPES = ['CAN_TEACH', 'WANTS_TO_LEARN'];
const PROFICIENCY_LEVELS = ['BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT'];
const USER_STATUSES = ['ACTIVE', 'INACTIVE', 'SUSPENDED'];
const SKILL_STATUSES = ['ACTIVE', 'INACTIVE'];
const SWAP_STATUSES = ['PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'COMPLETED'];
const PROJECT_STATUSES = ['DRAFT', 'ACTIVE', 'COMPLETED', 'ARCHIVED'];
const PROJECT_VISIBILITY = ['PUBLIC', 'PRIVATE'];
const PROJECT_ROLES = ['OWNER', 'MEMBER', 'CONTRIBUTOR'];
const CLASS_STATUSES = ['DRAFT', 'OPEN', 'FULL', 'ACTIVE', 'COMPLETED', 'CANCELLED'];
const CLASS_ROLES = ['INSTRUCTOR', 'LEARNER'];
const SESSION_STATUSES = ['SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED'];
const SESSION_ROLES = ['TEACHER', 'LEARNER'];

module.exports = {
  RELATIONSHIP_TYPES,
  PROFICIENCY_LEVELS,
  USER_STATUSES,
  SKILL_STATUSES,
  SWAP_STATUSES,
  PROJECT_STATUSES,
  PROJECT_VISIBILITY,
  PROJECT_ROLES,
  CLASS_STATUSES,
  CLASS_ROLES,
  SESSION_STATUSES,
  SESSION_ROLES,
};
